### PR TITLE
when* methods added: when, whenDistance, whenElement, etc

### PR DESCRIPTION
**Pull request by Tarabyte**
`when*` methods were added to spy instance.
- `when(breakPoint /*, rest*/)` - polymorphic method that accepts numbers, strings and even functions as a breakpoint;
- `whenDistance(distance)` - accepts numbers as a break point;
- `whenElement(selector, hitsTop: false)` - accepts string selector as a break point, triggers when element enters the viewport, unless `hitsTop` is `true`;
- `whenElementHitsTop(selector)` - alias for `whenElement(selector, true)`;
- `whenElementEnters(selector)` - alias for `whenElement(selector, false)`;
# Usage

``` javascript
scrollEvents('.foo')
   .whenDistance(10).changeClass('unscrolled', 'scrolled10')
   .whenElementEnters('.bar').changeText('unscrolled', '.bar enters the viewport')
   .whenElementHitsTop('.bar').changeText('.bar enters the viewport', '.bar hits top');
```

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@Tarabyte, this is really rad. Would you rebase on to https://github.com/ryanpcmcquen/scrollEvents/tree/useViewportHeight?

**Comment by Tarabyte** [comment]
Noob question. 
I have already pushed my commits to the origin to make a PR and rebase wont help. 
What should I do? :smiley:

**Comment by ryanpcmcquen** [comment]
Ha. Well your JavaScript makes me feel like a noob.  :wink:

This is what I would do, seems to work here:

```
git clone git@github.com:Tarabyte/scrollEvents.git
cd scrollEvents/
git checkout when-api
git remote add upstream git@github.com:ryanpcmcquen/scrollEvents.git
git pull --rebase upstream useViewportHeight
```

Then you can resolve the merge conflicts using something like `git mergetool`.

**Comment by Tarabyte** [comment]
I've made another PR #9

**Comment by ryanpcmcquen** [comment]
Closed in favor of #9. Thanks!

**Pull request closed without merging**
